server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php;

    access_log /var/log/nginx/cabinet_access.log;
    error_log  /var/log/nginx/cabinet_error.log warn;

    client_max_body_size 32m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_buffers 4 2560k;
        fastcgi_busy_buffers_size 2560k;
        fastcgi_temp_file_write_size 2560k;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
